---
name: Example Go Workflow
on:
  workflow_dispatch:
    inputs:
      example-input:
        description: Example input
        required: true
        type: string
env:
  EXAMPLE_WORKFLOW_VAR: Workflow level var
jobs:
  example-job:
    runs-on: [self-hosted]
    env:
      EXAMPLE_JOB_VAR: Job level var
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.16.1' # The Go version to download (if necessary)
      - name: echo
        run: |
          cd ./.github/workflows
          go mod init example.go
          go mod tidy
          go run example.go        
        env:
          EXAMPLE_STEP_VAR: Step level var
